### ISSUE TITLE
Set up deploying for server

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#109]

**Comment by alexdanilowicz** [comment]
FYI pricing for this looks like it will be $14 a month: https://www.heroku.com/pricing ($7 for non-sleep + $9 for db)

I'm somewhat surprised there isn't a way to spin up a simple server to store emails for free.

I guess someone needs to pay for the electricity.

**Comment by Teddarific** [comment]
I'm considering using Beanstalk instead - I'm wondering how we serve the actually app itself for download when it is ready, and s3 seems to make the most sense off the top of my head. In which case, would be nice to entirely be on AWS.

**Comment by alexdanilowicz** [comment]
"Beanstalk" 🤣. Just when I thought Silicon Valley ran out of cutesy names. 

Brilliant. Sounds good. Yeah, I'd love to know how VSCode is hosted on the VSCode website for example.

**Comment by Teddarific** [comment]
Ok did some poking around. I think serving the file could be done in two different ways:

**Solution 1: Served off server**:
We can just upload the files as part of the server, and the express server can just serve the file. This is the easier option, but has a few drawbacks.

- In our dream automated pipeline, this would involve checking-in the new build to the server code. This probably isn't a huge deal if we want to also change the web code to reflect the latest version (i.e. wording on the website like "Latest version: 1.3"), but might have some complications of checking in an artifact of a build
- Might have scale issues. This would mean every download opens and takes up a connection. If the build is decently sized (@alexdanilowicz  can you get an estimate here?), this would be a fairly big concern, especially off of Heroku. Could get pricy to scale.
- Overall, more clunky that the build has to be checked into the code and just doesn't feel quite ideal

**Solution 2: Served off s3**:
Every build uploads an artifact to s3. This feels cleaner in that we're uploading to a service meant for this purpose. Scales much better too. If we plan on using Beanstalk, we're staying in the same ecosystem. We also don't have to check in any artifacts into the code base. Any jobs would upload directly to s3, which looks easy via Github actions. Overall feels more professional. Drawbacks:

- New technology that we'd have to figure out, and feels almost like overkill when this is not the core product we're creating, and is in fact, just the tool to deliver our core product.
- Most likely more expensive

IF we go with Solution 1, we need to be prepared to spend $$ in the case we need to scale Heroku. Solution 2 would mean completely using AWS.

**Comment by alexdanilowicz** [comment]
@Teddarific .... or we host on Github? 👀 . Just saw this as an example: https://gather.town/download
<img width="1175" alt="Screen Shot 2021-03-19 at 12 49 55 AM" src="https://user-images.githubusercontent.com/29822597/111747870-13bdd780-884d-11eb-846e-589fa20ea7a1.png">

**Comment by alexdanilowicz** [comment]
https://docs.github.com/en/github/administering-a-repository/about-releases

**Comment by alexdanilowicz** [comment]
I vote we keep it simple and do that.

**Comment by alexdanilowicz** [comment]
Interesting how they are doing it: https://github.com/gathertown/gather-town-desktop-releases

**Comment by Teddarific** [comment]
Amazing find - this is the way to go
