### ISSUE TITLE
Sign & notarize a production build of the app

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#11]
See #9

**Comment by alexdanilowicz** [comment]
fyi @Teddarific The electron starter-pack uses some sort of "electron-builder" package, which apparently makes this easier. I would be sure to look into the starter pack docs first￼￼ regarding the electron builder package.

**Comment by alexdanilowicz** [comment]
I think the main task here is getting an Apple developers license.￼

**Comment by alexdanilowicz** [comment]
See https://www.electron.build/code-signing

**Comment by alexdanilowicz** [comment]
The work for this issue has changed drastically now that we are on electron-boiler-plate v2. We'll have to reassess the exact work to be done when the time comes.

**Comment by alexdanilowicz** [comment]
![Screen Shot 2021-01-09 at 8 34 17 PM](https://user-images.githubusercontent.com/29822597/104558268-68e42f80-55f7-11eb-8ebc-235346968147.jpeg)

For now, anyone could a packaged build following these steps.
