### ISSUE TITLE
Populate example text data

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#110]
We need to populate the stack of texts with real data and additionally add profile pictures.

**Comment by alexdanilowicz** [comment]
Just curious what do you mean by real data? Also, for the photos, I think we should use our real friends (with their permission) so we don't get sued.

the animoji faces (like yours is that pink teddy bear) might look quite nice

**Comment by alexdanilowicz** [comment]
Cause I think actual profile pics might look weird.

**Comment by Teddarific** [comment]
Ya i was gonna use our friends

**Comment by alexdanilowicz** [comment]
This issue should also include fixing the width/height of the texts. Right now, if a text is too long, it will be cut off. Same if it's not wide enough, which makes the texts look weird.

**Comment by alexdanilowicz** [comment]
> This issue should also include fixing the width/height of the texts. Right now, if a text is too long, it will be cut off. Same if it's not wide enough, which makes the texts look weird.

As a result of above ^, labeling as bug.

**Comment by alexdanilowicz** [comment]
Finally, `New` should not be an example in `New York Times`. Showcases that our analysis isn't perfect 😆
