### ISSUE TITLE
Fix Safari Desktop Compatibility

### ISSUE THREAD

**Issue by alexdanilowicz** [Left-on-Read/leftonread#112]
Unreal in 2021 we still have this issue. 😆 

Website has a few bugs on Safari:

- SVG on footer is messed up
- margins are super large (on Safari and Firefox)
- while doing this issue, would be good to checkout Firefox as well (see comment below)

Production URL: https://leftonread.me/

<img width="1440" alt="Screen Shot 2021-03-20 at 7 45 23 PM" src="https://user-images.githubusercontent.com/29822597/111892046-f0ae3780-89b4-11eb-9915-17602925081f.png">

<img width="1260" alt="Screen Shot 2021-03-20 at 7 49 51 PM" src="https://user-images.githubusercontent.com/29822597/111892107-76ca7e00-89b5-11eb-88ff-abacfb952ab1.png">

**Comment by alexdanilowicz** [comment]
On Firefox, svg in footer looks fine, but the Unique Analytics margins are too very large like Safari:
<img width="1294" alt="Screen Shot 2021-03-20 at 7 56 44 PM" src="https://user-images.githubusercontent.com/29822597/111892208-8dbda000-89b6-11eb-96d7-950b137baa1d.png">

**Comment by Teddarific** [comment]
The margins look ok to me, what margin specifically? 

The SVG issue is probably the same as the mobile issue.

**Comment by alexdanilowicz** [comment]
I feel like margin on Unique Analytics is very fat @Teddarific

**Comment by alexdanilowicz** [comment]
Resolved by #114
