### ISSUE TITLE
Fix Mobile Browser Compatibility

### ISSUE THREAD

**Issue by alexdanilowicz** [Left-on-Read/leftonread#113]
In the mobile browser (at least on iPhone8 both Safari and Chrome mobile):

- [ ] the svg in the footer seems to be stretched (probably same issue as https://github.com/Left-on-Read/leftonread/issues/112) 
- [ ] the text animation seems to be cut off slightly

**Comment by Teddarific** [comment]
Correct me if i'm wrong, but i think #112 can all be wrapped into "Fix Footer" basically?

**Comment by alexdanilowicz** [comment]
Sure, when making them I wanted to keep them separate in case Desktop / Mobile had diff solutions.
