### ISSUE TITLE
Fix that workflows don't run on forked copies

### ISSUE THREAD

**Issue by alexdanilowicz** [Left-on-Read/leftonread#127]
See https://github.com/Left-on-Read/leftonread/pull/124 as an example.

I believe the open-source standard is for contributors without push access to make forked repos. But if that's not the case, perhaps we could simplify this by giving everyone push access? 

Otherwise, we should get workflows running on forked copies as well.

**Comment by Teddarific** [comment]
Not possible to force someone to run workflows on their own copy if they don't follow our dev flow (e.g. creating a PR before merging into main), but I will make workflows run on PRs. IMO if someone's build fails, don't even bother reviewing.
