### ISSUE TITLE
Populate vercel deployment with env variables

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#142]
See `.env.sample` in `/web` to see what variables we need. Should all be grabbable from Google Firebase.

**Comment by alexdanilowicz** [comment]
Ok, so steps are:

1. Find values for these in Google Firebase: https://github.com/Left-on-Read/leftonread/blob/main/web/.env.example
2. put them in the vercel deployment
3. trigger a redeploy
4. QA? I imagine a success is seeing the webhook actually fire and the email in firebase.

**Comment by alexdanilowicz** [comment]
@Teddarific this is resolved.

Firestore DB after a test on vercel preview deploy:

<img width="1125" alt="Screen Shot 2021-04-10 at 5 19 33 PM" src="https://user-images.githubusercontent.com/29822597/114288065-0a292900-9a21-11eb-87f8-3001c52a641b.png">


Vercel envs (I set it for production, development, and preview):

<img width="811" alt="Screen Shot 2021-04-10 at 5 12 21 PM" src="https://user-images.githubusercontent.com/29822597/114288054-fda4d080-9a20-11eb-886f-c17b4792214f.png">
