### ISSUE TITLE
Add Filtering

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#202]
We need to re-implement filtering with the updated repository. We should be able to filter by the following things initially:

* Date
* Contact

We will build this feature into the "Adjust Filters" button
![image](https://user-images.githubusercontent.com/16343600/182715400-72c6ee9c-3866-41ac-8f04-5b4cc0839844.png)

The button should pop up a modal.

**Comment by alexdanilowicz** [comment]
@Teddarific are you sold on a modal? I think it should be a dropdown so users can see the filtering in real time. We can iterate, though.

**Comment by Teddarific** [comment]
@alexdanilowicz whatever is easier! I like dropdown too if there's the real estate for it
