### ISSUE TITLE
Sign & Notarize the app (enables auto-updates)

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#218]
1. https://github.com/electron/electron/blob/main/docs/tutorial/code-signing.md
2. https://www.electron.build/code-signing.html
3. And then we can easily configure auto-update: https://electron-react-boilerplate.js.org/docs/auto-update
4. Need to also include this work flow to publish on github: https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/.github/workflows/publish.yml

**Comment by alexdanilowicz** [comment]
I believe this is done @Teddarific ?
