### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by youngchen7** [Left-on-Read/leftonread#307]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to use this product on windows. I know everyone hates my green text bubbles when they pop up, and sometimes I get uninvited from group chats because I mess up all of the apple features, but I'd still like some insights into my messaging habits.

**Describe the solution you'd like**
A windows version of the app

**Describe alternatives you've considered**
I considered buying a mac, but they are expensive.

**Additional context**

**Comment by alexdanilowicz** [comment]
Hi, thanks for submitting issue. At this time, we will not be supporting Windows for iMessage analyzing, but it may be on the roadmap in the future. Thanks!
