### ISSUE TITLE
UX Bug: That dropdown for schedule messages is not the right choice

### ISSUE THREAD

**Issue by mattahorton** [Left-on-Read/leftonread#366]
**Describe the bug**
When I click on the dropdown for recipients when scheduling a message, a seemingly unsorted list of all of my contacts appears in a huge dropdown. Please just let me search.

The list seems to be _somewhat_ sorted by frequency of conversation but there are just random folks in there that don't make sense.

**To Reproduce**
1. Go to Scheduled Messages
2. Click on Schedule a Message
3. Click "Select a Contact"
4. See enormous unsorted list

**Expected behavior**
A searchable dropdown of contacts, ideally sorted reasonably (maybe by frequency?) if I've not searched.

**Screenshots**
<img width="526" alt="CleanShot 2022-09-09 at 10 47 23@2x" src="https://user-images.githubusercontent.com/5567285/189390189-8fbae535-97c0-4a29-ad32-4d8ebdab59f3.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.2.1

**Comment by alexdanilowicz** [comment]
Hey @mattahorton thanks for opening an issue! We'll improve the dropdown ASAP and allow searching.

**Comment by Teddarific** [comment]
@mattahorton Thanks for the feedback! I've gone ahead and closed the issue with #369. Let me know what you think when you get a minute to try it out!
