### ISSUE TITLE
Loading percentage doesn't reset on second initialization

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#388]
Loading percentage doesn't reset on second initialization. Refresh data for example will show 99% off the bat.

![image](https://user-images.githubusercontent.com/16343600/191621063-d8750ad0-23e5-4f30-a100-25fd612190b0.png)

**Comment by alexdanilowicz** [comment]
Fixed by https://github.com/Left-on-Read/leftonread/pull/381/commits/0fed293bbf97d21e2b045174e9620f9f395784f3#diff-6ca7e2c64a2eee9076fb5c1a22b9ffde5f718bca68d4ab5b2b8fb8820c841540R57
