### ISSUE TITLE
Sharing Improvements

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#403]
* Make "Share Button" a different colour so it's more prominent
* Tooltip on "Share" Button for first one and under adjust filters
* Add name if filtering for the "Copy to iMessage" button

**Comment by alexdanilowicz** [comment]
Resolved all of these except:

1) I tried share button as blue, I think it looks too weird. I think the tooltip under share will alert the user it exists, so I'm cool with leaving it as grey..

2) tooltip under adjust filters is tricky cause its technically already a popover / tooltip. will make new issue.
