### ISSUE TITLE
Flatten app directory

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#59]
Not a high priority.

It'd be nice to flatten the `app` directory so that the `electron` folder is basically the top level (but we can keep it named `app`). Is this possible?

RE: the `.vscode` folder, I don't much about this stuff, but if we want to keep it would be nice to hoist to top level (don't know implications of applying `electron` settings to other projects), or just remove it if it's not that useful.

**Comment by alexdanilowicz** [comment]
Yeah, I can do this. As long as `app/` top-level looks like this: https://github.com/electron-react-boilerplate/electron-react-boilerplate should be fine
