### ISSUE TITLE
Enable workflows for web

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#60]
As title suggests, we should set up workflows for web similar to app.

**Comment by alexdanilowicz** [comment]
A workflow that deploys on master would be sick.

Do you want to remove the lint/format workflows and do husky instead ? (Ball is in your court... work is also in your court for that one 😆 🤣 )

**Comment by Teddarific** [comment]
Actually, can we just get rid of husky entirely? Kinda annoying that it affects the entire repo @alexdanilowicz

**Comment by alexdanilowicz** [comment]
Ah, so you're team workflow now!? @Teddarific we have a convert! 🙏🏼 

yeah, go ahead and remove it. Husky was brought over from the ERB (Electron React boilerplate) setup
