### ISSUE TITLE
Add Emoji Chart to "Unique analytics" section

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#71]
Currently in the "Unique analytics" section we only have the "Top Received Words" chart.

![image](https://user-images.githubusercontent.com/16343600/109404649-e2707c80-791c-11eb-8fd3-ae503f29500c.png)

Let's add in a "Top Emojis" chart. We should add it so it's a carousel with left / right arrows to scroll through each different chart. You'll also probably have to add another hard-coded data field to the Texts. Don't worry too much about the actual content since I plan on going through and handling that near the end.

**Comment by alexdanilowicz** [comment]
@Teddarific do you think it should be part of the Infographic component? The amination makes it a bit challenging. I was thinking of making another "section" aka _another_ Infographic component... which would say something like "LEARN ABOUT YOURSELF" and then a chart of the emojis.

Or do you want the emoji chart in the same "UNIQUE ANALYTICS" section. I just think that might get messy with animation.

**Comment by Teddarific** [comment]
I was imagining in the same `Unique Analytics` section, but up to you if you also want to change the title / description stuff. I'm thinking the carousel can shuffle through either just the chart, or the chart and the text.

RE: The animation, is it the carousel animation you're worried about? Because yeah, that might be a little tricky / time consuming. But if you're just worried about animating the chart, check out the `useTextData` hook: https://github.com/Left-on-Read/leftonread/blob/main/web/src/components/sections/Infographic.tsx#L114. This is basically the driver behind the texts, and all the underlying data (like how many each of word etc). So if you add another piece of state like `const [receivedEmojis, setReceivedEmojis]` and then copy how the logic works for `receivedWords`, the infra there should handle all the updating data.

Then, when the component uses `useTextData`, you should return another field in that object like `receivedEmojis`, and pass that data straight into your new chart! Lmk if that makes sense -

**Comment by alexdanilowicz** [comment]
>RE: The animation, is it the carousel animation you're worried about?

No, your TextStack animation is what I was referring to. @Teddarific

**Comment by alexdanilowicz** [comment]
But ok, what I'm hearing is 100% integration Favorite Emojis chart with the TextStack animation. Will do.

**Comment by Teddarific** [comment]
Yeah - I can cook up a quick Figma if it would help, but imagine the Favorite Emoji chart basically replacing the Receiving Word chart. I'm thinking like a right arrow next to the chart that you can click and the only thing that will change is the chart from the Receiving Words chart to the Emojis Chart

**Comment by Teddarific** [comment]
Damn reading through that component, the code is kinda ass. Sorry about that lol. Too much styling.

**Comment by alexdanilowicz** [comment]
OHHHH A CAROUSEL OF CHARTS!!!!!!!!!

Got it.

I thought it would be two charts and a _CAROUSEL_ of data.

**Comment by alexdanilowicz** [comment]
I forgot that the left and right arrows were non-native to chart.js. I suppose we'll recreate what we did the first time, i.e., https://github.com/Teddarific/client-leftonread/blob/master/src/components/analytics/graphs/top_five_words_chart.js#L53-L65

**Comment by Teddarific** [comment]
@alexdanilowicz  To clarify here, I think you should just wrap two different charts with a carousel instead of implementing the scroll behavior into the chart. Like https://github.com/brainhubeu/react-carousel for example, but instead of pictures two different charts.

**Comment by alexdanilowicz** [comment]
I think this is a won't do or is extremely low priority in terms of the marketing site. Other high priority issues IMO: https://github.com/Left-on-Read/leftonread/issues/115, https://github.com/Left-on-Read/leftonread/issues/80, https://github.com/Left-on-Read/leftonread/issues/110

**Comment by Teddarific** [comment]
Closing because of deprioritization.
