### ISSUE TITLE
Adding Contact Us Functionality

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#72]
We'll have a link to Contact Us in the Footer. I'm open to how we implement this. A few options off the top of my head:

- Natively implementing a modal ourselves with a form that submits it to our server and stores in Mongo
- Integrating a Typeform
- If we're really lazy, just link to an email

**Comment by alexdanilowicz** [comment]
I think we should do Github issues for this @Teddarific, i.e, Contact us links to a Github issue template. That's the primary way open-source software does it I feel.

Leetcode even does it. For example: https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/2563
