### ISSUE TITLE
Add TOS and Privacy Policy Pages and then Link Them in Footer

### ISSUE THREAD

**Issue by alexdanilowicz** [Left-on-Read/leftonread#79]
Didn't see this anywhere in the code. Is React Router still your preferred way of implementing this in this way @Teddarific ?

**Comment by Teddarific** [comment]
Since we're using Next.js, this should suffice: https://nextjs.org/docs/api-reference/next/link

But good call out, this does indeed need to be done.

**Comment by alexdanilowicz** [comment]
Resolved in PR #96
