### ISSUE TITLE
Prompt for full disk permissions

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/leftonread#8]
Kind of blocked by design, but we should set up the main framework of the user flow. We can copy over the old copy / flow from the original site for now.

**Comment by Teddarific** [comment]
Here are the initial "Get started" designs: https://www.figma.com/file/f6D3IvytolE8zFaImNhXxQ/Left-on-Read-2.0?node-id=1%3A919

Based off of investigations from #9, where it seems like we can directly query the user's data with their permissions

**Comment by alexdanilowicz** [comment]
Nice. Added some comments to the design. Bumping this down to medium priority, as not everything can be very high. 😂

**Comment by alexdanilowicz** [comment]
Bumping this to high priority! User flows don't make themselves!

**Comment by alexdanilowicz** [comment]
Let's think deeply about this before we implement it.

As an MVP, the bare minimum we need is to ask users for full disk access.

V2, we should want to give them the ability to copy the chat.db & address.db  (or .vcf) onto their Desktop instead.

In either case, I think there should only be one page... so 1 click for the user to see their analytics. We have to remember the beauty of _Left On Read Electron edition_ ™️ : it runs automatically. There is no need for prompting, nor clicking, nor stalling.

**Comment by Teddarific** [comment]
Closing for #92
