### ISSUE TITLE
Should we add an "About Us" section to marketing website?

### ISSUE THREAD

**Issue by alexdanilowicz** [Left-on-Read/leftonread#80]
Doesn't have to be its own page... but maybe that's best.

I was thinking that we should make it clear that this is the same Left on Read from reddit, from Dartmouth, and the same Left on Read that previously made you upload your chat.db on the Internet. 

Thoughts? @Teddarific

**Comment by Teddarific** [comment]
Yeah this would be nice if we have the bandwidth.

**Comment by Teddarific** [comment]
Closing because of deprioritization.
